### ISSUE TITLE
Add link to source on the website

### ISSUE THREAD

**Issue by Soundtoxin** [OpenShopChannel/Site#1]
I had trouble finding the site source, and still can't find source for the homebrew browser. I clicked the link to the CLI tool, saw that was GPLv3, checked what other repos that author had, found the OpenShopChannel GitHub from there. It would be good to have a few buttons by things to get to their source easily. My first impression was "Open is in the name, but I'm struggling to find sources".

**Comment by dhtdht020** [comment]
On the work in progress revamp for the website, at beta.oscwii.org, there's a button that links to the GitHub organization in the top right corner. As for the current website, it will be replaced very soon.

The source for the Homebrew Browser can be found [on codemii](http://www.codemii.com/HBB%20Source%20v0.3.9e.zip).
It's not here on GitHub since the only modification from the Open Shop Channel is replaced URLs, and we are not a proper fork, more like a secondary server.

**Comment by dhtdht020** [comment]
It can also be found [right here](https://github.com/OpenShopChannel/OpenShopChannel/) on the GitHub now.

**Comment by Soundtoxin** [comment]
Alright, looks okay on the beta site, I suppose. Could be good to have "source" or "sources" written somewhere for someone trying to quickly search the page's text as well, but I'll close my issue now.
